version: '3'
services:
  nginx:
    image: bitnami/nginx:1.25.3
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /opt/services/conf/nginx.conf:/opt/bitnami/nginx/conf/nginx.conf
      - /opt/services/certs:/etc/nginx/certs
      - /opt/services/nginx-logs:/opt/bitnami/nginx/logs/
    user: root:root
    networks:
      - services_net

  postgres:
    image: postgres:alpine3.18
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: wiki
      POSTGRES_PASSWORD: wikijsrocks
      POSTGRES_USER: wikijs
    volumes:
      - /opt/services/db-data:/var/lib/postgresql/data
    networks:
      - services_net

  wiki:
    image: requarks/wiki:2.5.299
    container_name: wiki
    depends_on:
      - postgres
    environment:
      DB_TYPE: postgres
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: wikijs
      DB_PASS: wikijsrocks
      DB_NAME: wiki
    restart: unless-stopped
    volumes:
      - /opt/services/sideload:/wiki/data/sideload
      - /opt/services/config.yml:/wiki/config.yml
    networks:
      - services_net

networks:
  services_net:
    driver: bridge
